### ISSUE TITLE
Problem when no namespace associate with the Signature

### ISSUE THREAD

**Issue by pitbulk** [robrichards/xmlseclibs#58] opened 2015-07-15 15:57 UTC
I have the following XML (prettyprinted):
```
<?xml version="1.0"?>
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_7b8df9609dfcb6b735ce90ea50a975b1979f5f14cd" Version="2.0" IssueInstant="2014-12-01T23:05:49Z" Destination="https://pitbulk.no-ip.org/newonelogin/demo1/index.php?acs" InResponseTo="ONELOGIN_cca5c4b75c18612ca8cd5fbbcde3d32f9d092370">
  <saml:Issuer>https://pitbulk.no-ip.org/simplesaml/saml2/idp/metadata.php</saml:Issuer>
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
  </samlp:Status>
  <saml:Assertion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" ID="_2ff35216bf2e1021778885fadd78ac5d6f82f83f16" Version="2.0" IssueInstant="2014-12-01T23:05:49Z">
    <saml:Issuer>https://pitbulk.no-ip.org/simplesaml/saml2/idp/metadata.php</saml:Issuer>
    <Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <SignedInfo>
        <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
        <Reference URI="#_2ff35216bf2e1021778885fadd78ac5d6f82f83f16">
          <Transforms>
            <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
          </Transforms>
          <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
          <DigestValue>KRTtSoaoB8ypMqC2yZlb2AzRGRo=</DigestValue>
        </Reference>
      </SignedInfo>
      <SignatureValue>0nG/mSAzS01TfID3oE/v+uyLDloI6p8invoWJO/X2aotI8qNGFK2wvtsEhXZt7WHf2On5D/Ui/KDnBsL+iwSytajZ/M/3equVCG8LpHo4Zd1dAQJqnhIrB3oT4NEdwN3ePR1wBNX+EmdbQ/CBgG1T0jzLocdPtIP1LollBuDSaA=</SignatureValue>
      <KeyInfo>
        <X509Data>
          <X509Certificate>MIICbDCCAdWgAwIBAgIBADANBgkqhkiG9w0BAQ0FADBTMQswCQYDVQQGEwJ1czETMBEGA1UECAwKQ2FsaWZvcm5pYTEVMBMGA1UECgwMT25lbG9naW4gSW5jMRgwFgYDVQQDDA9pZHAuZXhhbXBsZS5jb20wHhcNMTQwOTIzMTIyNDA4WhcNNDIwMjA4MTIyNDA4WjBTMQswCQYDVQQGEwJ1czETMBEGA1UECAwKQ2FsaWZvcm5pYTEVMBMGA1UECgwMT25lbG9naW4gSW5jMRgwFgYDVQQDDA9pZHAuZXhhbXBsZS5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOWA+YHU7cvPOrBOfxCscsYTJB+kH3MaA9BFrSHFS+KcR6cw7oPSktIJxUgvDpQbtfNcOkE/tuOPBDoech7AXfvH6d7Bw7xtW8PPJ2mB5Hn/HGW2roYhxmfh3tR5SdwN6i4ERVF8eLkvwCHsNQyK2Ref0DAJvpBNZMHCpS24916/AgMBAAGjUDBOMB0GA1UdDgQWBBQ77/qVeiigfhYDITplCNtJKZTM8DAfBgNVHSMEGDAWgBQ77/qVeiigfhYDITplCNtJKZTM8DAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBDQUAA4GBAJO2j/1uO80E5C2PM6Fk9mzerrbkxl7AZ/mvlbOn+sNZE+VZ1AntYuG8ekbJpJtG1YfRfc7EA9mEtqvv4dhv7zBy4nK49OR+KpIBjItWB5kYvrqMLKBa32sMbgqqUqeF1ENXKjpvLSuPdfGJZA3dNa/+Dyb8GGqWe707zLyc5F8m</X509Certificate>
        </X509Data>
      </KeyInfo>
    </Signature>
    <saml:Subject>
      <saml:NameID SPNameQualifier="https://pitbulk.no-ip.org/newonelogin/demo1/metadata.php" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_486af16ab7b1bb20c888be338e5dd19abed682d471</saml:NameID>
      <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml:SubjectConfirmationData NotOnOrAfter="2024-06-04T04:25:49Z" Recipient="https://pitbulk.no-ip.org/newonelogin/demo1/index.php?acs" InResponseTo="ONELOGIN_cca5c4b75c18612ca8cd5fbbcde3d32f9d092370"/>
      </saml:SubjectConfirmation>
    </saml:Subject>
    <saml:Conditions NotBefore="2014-12-01T23:05:19Z" NotOnOrAfter="2024-06-04T04:25:49Z">
      <saml:AudienceRestriction>
        <saml:Audience>https://pitbulk.no-ip.org/newonelogin/demo1/metadata.php</saml:Audience>
      </saml:AudienceRestriction>
    </saml:Conditions>
    <saml:AuthnStatement AuthnInstant="2014-12-01T23:05:49Z" SessionNotOnOrAfter="2014-12-02T07:05:49Z" SessionIndex="_1f1f4501c8077985135667801b97bd210dc4ca867e">
      <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
      </saml:AuthnContext>
    </saml:AuthnStatement>
    <saml:AttributeStatement>
      <saml:Attribute Name="uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">test</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="mail" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">test@example.com</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="cn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">test_cn</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="sn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">waa2</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="eduPersonAffiliation" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">user</saml:AttributeValue>
        <saml:AttributeValue xsi:type="xs:string">manager</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="company" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">onelogin</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="street" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">street example</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="city" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">city example</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="country" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">country example</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="state" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">state example</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="zip" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">32323</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="telephone" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">878732323</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="fax" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">828732323</saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>
  </saml:Assertion>
</samlp:Response>
```

If I try to validate the Signature of the XML it will fail ("Cannot locate Signature Node") because the Signature does not contain the ds:Signature expected in that library. Do you know the best approach to solve that issue? May I transform the XML before try to validate it or should that library accept xpath queries without namespace?

**Comment by robrichards** [comment] 2015-07-16 13:20
Where did you get that document? The Signature element *must* be associated with the http://www.w3.org/2000/09/xmldsig# namespace (wether its defined as the global namespace via xmlns="http://www.w3.org/2000/09/xmldsig#" or via a namespace prefix (such as the ds prefix I use), xmlns:ds="http://www.w3.org/2000/09/xmldsig#". Based on that document it is not a valid XML Signature

**Comment by robrichards** [comment] 2015-07-24 17:19
Closing this out as the document itself is bad (Signature not in any namespace) and cannot be validated, so not a bug

**Closed by robrichards** 2015-07-24 17:19 UTC
