### ISSUE TITLE
openssl_random_pseudo_bytes is insecure

### ISSUE THREAD

**Issue by relaxnow** [robrichards/xmlseclibs#97] opened 2016-03-23 09:09 UTC
It appears that openssl_random_pseudo_bytes is, in a large number of configurations, not safe for cryptographic use: https://github.com/paragonie/random_compat/issues/96 .

It might be better to switch to a PHP7 polyfill: https://github.com/paragonie/random_compat

**Comment by willemstuursma** [comment] 2017-05-22 11:45
@robrichards I'm willing to pick this up, if you'll merge the changes and release a new version. Got some time for this from my employer. Let me know what'd you think.

**Comment by robrichards** [comment] 2017-05-25 15:12
Dupe of #100

**Closed by robrichards** 2017-05-25 15:12 UTC
