### ISSUE TITLE
HHVM seg fault

### ISSUE THREAD

**Issue by tmilos** [robrichards/xmlseclibs#87] opened 2015-12-07 17:00 UTC
HHVM build appears to hang, but after some [debugging](https://travis-ci.org/tmilos/xmlseclibs/jobs/95223265) I have found it actually crashes on test `xmlsec-decrypt-content.phpt` with a seg fault. HHVM version it happened on travis-ci is 3.6.6, but in my local I have 3.10.1 where it is not happening.  

Don't know how to fix this, just reporting what I have found, in case somebody can help and fix it on hhvm 3.6.6 or do some travis-ci magic.

```
$ hhvm tests/xmlsec-decrypt-content.phpt && echo ok
--TEST--
Basic Decryption: Content
--FILE--
AOESP_SHA1: Passed
AOESP_SHA1_CONTENT: Passed
--EXPECTF--
AOESP_SHA1: Passed
AOESP_SHA1_CONTENT: Passed
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.3051.log
/home/travis/build.sh: line 45:  3051 Segmentation fault      (core dumped) hhvm tests/xmlsec-decrypt-content.phpt

The command "hhvm tests/xmlsec-decrypt-content.phpt && echo ok" exited with 139.
```

**Comment by thijskh** [comment] 2016-02-23 18:28
So the problem is a bug in HHVM which has been fixed in newer versions. I attempted to convince Travis to build with a newer HHVM but this is not currently possible in a straightforward way.

Alternative is to install a newer HHVM via sudo/apt-get, or to mark hhvm as allowed failure until Travis has the newer version available.

**Comment by thijskh** [comment] 2016-12-03 16:14
This seems to have been fixed by upgrading HHVM. This issue can be closed.

**Comment by skymeyer** [comment] 2016-12-15 03:23
The changes in `.travis.yml` as proposed in https://github.com/robrichards/xmlseclibs/pull/101 should fix the runs on travis using recent HHVM versions.

**Comment by thijskh** [comment] 2017-06-20 13:48
This issue can be closed: fixed in HHVM

**Closed** 2017-08-08 12:06 UTC
